name: .NET Core Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: IntegrationTesting.sln                         # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: RestAPITest\RestAPITest.csproj               # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.
      Wap_Project_Directory: IntegrationTesting\RestAPI    # Replace with the Wap project directory relative to the solution, i.e. MyWpfApp.Package.
      Wap_Project_Path: IntegrationTesting\RestAPI.csproj                   # Replace with the path to your Wap project, i.e. MyWpf.App.Package\MyWpfApp.Package.wapproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the solution
    - name: Execute integration tests
      run: |
        dotnet build
        dotnet test --logger "junit;LogFileName=TestResults.xml"   

    - name: List directory
      run: ls RestAPITest
          
    # Creates easy to read test summary
    - name: TestForest Dashboard
      uses: test-summary/action@v2.4
      with:
        paths: "RestAPITest/TestResults/TestResults.xml"
        show: "all"
        output: test-summary.md
      if: always()
      
    - name: Upload test summary
      uses: actions/upload-artifact@v4
      with:
        name: test-summary
        path: test-summary.md
      if: always()
